name: Build & Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 23.x]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Flow
        run: npm run flow
      - name: Post-Test
        run: npm run posttest
      - name: Test
        run: npm run test
      - name: Test examples
        run: npm run test:examples
      - name: Report Test Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
